### ISSUE TITLE
verifying invocation seems to require capability.controller, whereas spec says it is optional

### ISSUE THREAD

**Issue by gobengo** [digitalbazaar/zcap#86]
I got an error like this while verifying a zcap invocation:

```
Error: Capability controller not found.
    at getControllers (/PROJECT/node_modules/@digitalbazaar/zcap/lib/utils.js:38:11)
    at Module.isController (/PROJECT/node_modules/@digitalbazaar/zcap/lib/utils.js:55:23)
    at CapabilityInvocation._runChecksAfterChainVerification (/PROJECT/node_modules/@digitalbazaar/zcap/lib/CapabilityInvocation.js:304:15)
    at CapabilityInvocation.validate (/PROJECT/node_modules/@digitalbazaar/zcap/lib/CapabilityProofPurpose.js:205:41)
```

I believe the error is thrown from [around here when CapabilityInvocation._runChecksAfterChainVerification tries to check the controller of the invoked zcap](https://github.com/digitalbazaar/zcap/blob/main/lib/CapabilityInvocation.js#L300)

The capability being invoked is like this. Note: there is no controller, only an invoker. The parentCapability has a controller that signed the delegation to the invoker.
This seems to be allowed per [example 1 of zcap-spec](https://w3c-ccg.github.io/zcap-spec/#example-1).
```
{
  "id": 'urn:uuid:09e1db28-6ceb-4f25-873b-d864720c4d05',
  "invoker": "did:key:z6MkeTt9T7qzCXKQU8LoiyWoZQ7KMK6EH7pfFSzweCnr698r",
  "parentCapability": "urn:uuid:00346e75-194d-40cb-b331-df9ce1be3ae4",
  "proof": {
      type: 'Ed25519Signature2020',
      created: '2024-12-04T21:12:43Z',
      verificationMethod: 'did:key:z6MkmUXq7iWyEDfTGk3eg8U1KcRJR8VhaMFVKAbeRWPkrUY1#z6MkmUXq7iWyEDfTGk3eg8U1KcRJR8VhaMFVKAbeRWPkrUY1',
      proofPurpose: 'capabilityDelegation',
      capabilityChain: [Array],
      proofValue: 'z64mhXhfzwTUkk9M9Weq4Ess4R4Q5T9nRRqfeVHTnnQKZ2J9D2tanMn1UG1Gi3SFLg5F23Uqmw98gfM5j8Kbcp7Qt'
    }
}
```

The invoked capability's parentCapability is like
```
{
  "id": "urn:uuid:00346e75-194d-40cb-b331-df9ce1be3ae4",
  "controller": "did:key:z6MkmUXq7iWyEDfTGk3eg8U1KcRJR8VhaMFVKAbeRWPkrUY1",
  "parentCapability": "urn:zcap:root:...."
}
```

Is it valid per the spec to invoke a capability like example 1 that has no `controller`? (iiuc this is the best way of delegating a zcap in a way that it can be invoked but not further delegated)

If so, am I using this `zcap` library correctly to verify such invocations?

Thank you,
bengo

**Comment by gobengo** [comment]
Hmm. I found this, which is helpful. It seems to document an intentional deviation by this library from the spec. https://github.com/digitalbazaar/zcap/blob/62f6655ffd68c74e40785af76735f76b8cfc27b8/CHANGELOG.md?plain=1#L118

**Comment by dlongley** [comment]
Ah, yes, this is a spec bug, I've filed an issue here:

https://github.com/w3c-ccg/zcap-spec/issues/49

The `invoker` and `delegator` properties were replaced by a single property `controller`, because you can't separate those powers. If you can invoke a zcap, you can delegate it -- either using standard tools or by going out of your way to share the key or putting an API up around the key that can invoke it (with zcaps to access it), when delegating the standard way would have been cleaner and simpler. If you can delegate a zcap, you can invoke it, because you can always just delegate to a new key you create.

**Comment by gobengo** [comment]
ty @dlongley 

closing to discuss on spec https://github.com/w3c-ccg/zcap-spec/issues/49
